"""base: esquema completo segun modelos actuales

Revision ID: 0001
Revises: 
Create Date: 2026-08-30 02:28:09.101823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_event_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('is_top_inning', sa.Boolean(), nullable=False),
    sa.Column('batter_id', sa.String(), nullable=False),
    sa.Column('pitcher_id', sa.String(), nullable=False),
    sa.Column('batter_name', sa.String(), nullable=True),
    sa.Column('pitcher_name', sa.String(), nullable=True),
    sa.Column('balls', sa.Integer(), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('outs', sa.Integer(), nullable=True),
    sa.Column('runners_on_base', sa.JSON(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_event_logs_game_id'), 'game_event_logs', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_event_logs_id'), 'game_event_logs', ['id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('home_user_id', sa.String(), nullable=False),
    sa.Column('away_user_id', sa.String(), nullable=False),
    sa.Column('current_inning', sa.Integer(), nullable=True),
    sa.Column('is_top_inning', sa.Boolean(), nullable=True),
    sa.Column('outs', sa.Integer(), nullable=True),
    sa.Column('balls', sa.Integer(), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('score_home', sa.Integer(), nullable=True),
    sa.Column('score_away', sa.Integer(), nullable=True),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_id'), 'game_sessions', ['id'], unique=False)
    op.create_table('tactic_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=False),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tactic_cards_id'), 'tactic_cards', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('is_cpu', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_is_cpu'), 'teams', ['is_cpu'], unique=False)
    op.create_table('player_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'BRONZE', 'SILVER', 'GOLD', 'DIAMOND', name='cardrarity'), nullable=False),
    sa.Column('is_two_way', sa.Boolean(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('control', sa.Integer(), nullable=True),
    sa.Column('movement', sa.Integer(), nullable=True),
    sa.Column('repertoire', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_cards_id'), 'player_cards', ['id'], unique=False)
    op.create_index(op.f('ix_player_cards_team_id'), 'player_cards', ['team_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('favorite_team_id', sa.String(length=3), nullable=True),
    sa.Column('has_completed_onboarding', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_card_inventories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['player_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_card_inventories_card_id'), 'user_card_inventories', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_card_inventories_user_id'), 'user_card_inventories', ['user_id'], unique=False)
    op.create_table('user_lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('slots', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_lineups_id'), 'user_lineups', ['id'], unique=False)
    op.create_index(op.f('ix_user_lineups_user_id'), 'user_lineups', ['user_id'], unique=False)
    op.create_table('user_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=3), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('stadium_name', sa.String(length=50), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('logo_id', sa.String(length=50), nullable=True),
    sa.Column('base_franchise', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_teams_id'), 'user_teams', ['id'], unique=False)
    op.create_index(op.f('ix_user_teams_user_id'), 'user_teams', ['user_id'], unique=True)
    op.create_table('user_wallets',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stamps', sa.Integer(), nullable=True),
    sa.Column('gems', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_wallets')
    op.drop_index(op.f('ix_user_teams_user_id'), table_name='user_teams')
    op.drop_index(op.f('ix_user_teams_id'), table_name='user_teams')
    op.drop_table('user_teams')
    op.drop_index(op.f('ix_user_lineups_user_id'), table_name='user_lineups')
    op.drop_index(op.f('ix_user_lineups_id'), table_name='user_lineups')
    op.drop_table('user_lineups')
    op.drop_index(op.f('ix_user_card_inventories_user_id'), table_name='user_card_inventories')
    op.drop_index(op.f('ix_user_card_inventories_card_id'), table_name='user_card_inventories')
    op.drop_table('user_card_inventories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_player_cards_team_id'), table_name='player_cards')
    op.drop_index(op.f('ix_player_cards_id'), table_name='player_cards')
    op.drop_table('player_cards')
    op.drop_index(op.f('ix_teams_is_cpu'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_tactic_cards_id'), table_name='tactic_cards')
    op.drop_table('tactic_cards')
    op.drop_index(op.f('ix_game_sessions_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_game_event_logs_id'), table_name='game_event_logs')
    op.drop_index(op.f('ix_game_event_logs_game_id'), table_name='game_event_logs')
    op.drop_table('game_event_logs')
    # ### end Alembic commands ###
