"""Aliases legacy; usar performance_tier_2 en código nuevo."""

from etl.config.performance_tier_2 import (
    OVERALL_RATING_METRIC,
    PERFORMANCE_TIER_MODEL_VERSION,
    PERFORMANCE_TIER_THRESHOLDS,
)


RARITY_MODEL_VERSION = PERFORMANCE_TIER_MODEL_VERSION
RARITY_THRESHOLDS = PERFORMANCE_TIER_THRESHOLDS
